### ISSUE TITLE
Difference CAD and reconst

### ISSUE THREAD

**Issue by KSImperial** [DLR-RM/AugmentedAutoencoder#116]
Can anyone explain the difference between CAD mode and reconst mode in the cfg?

**Comment by AminSeffo** [comment]
Hello @KSImperial,

you can see the difference below between CAD (left side) and reconst (right side) of  [tless/obj_000001](https://bop.felk.cvut.cz/media/data/bop_datasets/tless_models.zip):
![Screenshot from 2022-08-05 08-53-48](https://user-images.githubusercontent.com/92951154/183020001-f83b1378-08b1-4498-bc41-a3aedb3b312c.png)
But I dont really know how to export the model to reconst since both versions have the same extension `.ply`.

I would also be interested in how it works and how to center the objects with Blender.

**Comment by KSImperial** [comment]
Thanks for the reply @AminSeffo. Do you know if selecting cad/reconst has any effect on training or creating the codebooks?

**Comment by AminSeffo** [comment]
> Thanks for the reply @AminSeffo. Do you know if selecting cad/reconst has any effect on training or creating the codebooks?

Sorry, I even don't know if this affects the training or the codebook

**Comment by MartinSmeyer** [comment]
I observed similar performance for reconst/CAD, check e.g. figure 4.11 here:
https://elib.dlr.de/117228/1/Masterthesis.pdf

The reconstruction includes texture information and the CAD model usually has better geometry info. What is better depends on the object.
