### ISSUE TITLE
The requirement of graphic card memory?

### ISSUE THREAD

**Issue by shawnlin427** [DLR-RM/AugmentedAutoencoder#120]
Amazing 6D estimation tools for CAD model, thanks!
However, I run into OOM trouble while training my custom model on GTX1650 (4GB memory), even I modified the batch size to 1. Have you tried to train the model on a low video memory device?  Your answer is vital for me, thanks!

**Comment by MartinSmeyer** [comment]
Hey @0smile,

sorry I have not trained on such a small GPU but it should be just enough if it is empty.

Otherwise what you can also do is reduce the size of the encoder/decoder a bit:

https://github.com/DLR-RM/AugmentedAutoencoder/blob/9f0a56f622fabf6200d9f034fcb2eef106997118/auto_pose/ae/cfg/train_template.cfg#L52
