### ISSUE TITLE
How do I train with multiple models?

### ISSUE THREAD

**Issue by sjtuytc** [DLR-RM/AugmentedAutoencoder#14]
How do I train with more than one models? For there is only one model that can be placed in to the config file.

**Comment by MartinSmeyer** [comment]
The AAEs are only trained on single objects. However, you can test using several single object encoders.

Naively training on several objects has rather limited success since in this case the encoders do not only have to relate different views but also need to classify the object views. This is currently done by the detector. 

That being said, we will soon publish an approach that lets an encoder encode the 3D orientation of multiple objects and even untrained objects. But without problems you can load many encoders into the gpu memory at inference time. See the test section.
