### ISSUE TITLE
'not enough visible points' when testing with TejaniDB milk object

### ISSUE THREAD

**Issue by HsiaoTsan** [DLR-RM/AugmentedAutoencoder#39]
Thank you for your brilliant masterpiece and making it open-sourced.
I have successfully trained AAE on TejaniDB object "milk", when I run `ae_eval`, the code warns me `not enough visible points`, then the image shown does not render the estimation object. I checked the code it is in [auto_pose/eval/icp_utils.py, line 265.](https://github.com/DLR-RM/AugmentedAutoencoder/blob/master/auto_pose/eval/icp_utils.py#L265)

```
    if len(real_depth_pts) < len(synthetic_pts)/8.:
        print 'not enough visible points'
```

It seems that the number of real depth points is not enough. I have changed the if statement to  `len(real_depth_pts) < len(synthetic_pts)/800.`, but the warning still exists. 
What should I do?
Thank you in advance!

**Comment by MartinSmeyer** [comment]
Hi HsiaoTsan,
thank you and sorry for my late reply. 
This is within the iterative depth refinement (ICP) and happens when they are not enough matches between the rendered model and the scene.
Does it occur every time? 
How is the output if you run your code without the ICP, i.e. setting  `icp = False` in you eval config? 
What is the value in your training cfg for vertex_scale?

**Comment by HsiaoTsan** [comment]
Hi Martin,
thank you for your reply and sorry I'm late.
It happens to all TejaniDB object 'milk', no estimated pose will be rendered into the scene image. 
 It happens every time. If I set the `icp = False` the output is as normal as TLESS datasets.
the vertex_scale is 1 in the training cfg, as the point cloud .ply file is already in millimeter.

I have not worked in TejaniDB dataset for a while, you may close this issue if you want to.

Thank you.
